name: protospacemesh
description: A new Flutter package project.
version: 0.0.6
homepage: https://github.com/andreivdev/protospacemesh

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fixnum: ^1.0.0
  grpc: ^3.0.0
  protobuf: ^2.0.0
